export {default as Login} from './Login/Index'
export {default as Menu} from './Menu/Index'
export {default as Customer} from './Customer/Index'
export {default as Table} from './Table/Index'
export {default as Edit} from './Edit/Index'
export {default as AddMenu} from './Add/menu/Index'
export {default as AddCustomer} from './Add/customer/Index'
export {default as AddTable} from './Add/table/Index'