export {default as Login} from './Login/Index'
export {default as Menu} from './Menu/Index'
export {default as Customer} from './Customer/Index'
export {default as Table} from './Table/Index'
export {default as Edit} from './Edit/Index'