export const ACTION_TYPE = {
    menu: {
        CHANGE_MENU_NAME: 'CHANGE_MENU_NAME',
        CHANGE_PRICE: 'CHANGE_PRICE'
    },
    customer: {
        CHANGE_CUSTOMER_NAME: 'CHANGE_CUSTOMER_NAME',
        CHANGE_CUSTOMER_EMAIL: 'CHANGE_CUSTOMER_EMAIL',
        CHANGE_CUSTOMER_ADDRESS: 'CHANGE_CUSTOMER_ADDRESS'
    },
    table:{
        CHANGE_NUMBER:'CHANGE_NUMBER',
        CHANGE_STATUS:'CHANGE_STATUS'
    }
}